export const allRODerailsDummy = {
  paging: {
    page: 1,
    count: 10,
    total: 72,
  },
  content: [
    {
      roCode: "125242",
      roName: "SUPER SERVICE STATION",
      projectPhase: "P1",
      automaticVendor: "bahwan cybertek",
      tempCloseROModernisation: "No",
      roType: "COCO",
      validLeaseDate: "26 Dec 2035",
      roCategory: "Service station",
      salesArea: "Chennai",
      region: "Chennai",
      zone: "Sounth",
      headOffice: "Chennai",
      address: "Amaravathi Nagar, Udume=ulpet taluk",
      city: "Andigondannur",
      district: "Chennai",
      state: "tamilNadu",
      pincode: "642102",
      dealerName: "GOEL BALRAM",
      delearPhoneNumber: "04252 256 296",
      delearMobileNumber: "9526866705",
      hpclEmailId: "test@gmail.com",
      wmnValidityDate: "jun 20 2029",
      tinNumber: "1212333454333",
      ipAddredd: "122.165.72.86",
      vsatBrodmbandSdvanSimId: "34343434343434",
      vsatBrodmbandSdvanSimId2: "34343434343434",
      lastRoCommunicatedDate: "Aug 21 3023 11:54 AM",
      roStatus: "Active",
      fzdStatsu: "Active",
      locationType: "Urbana",
      highwayNumber: "66",
      highwayState: "12",
      pesoLienseNumber: "AB23233442217878977",
      pesoValidityTillDate: "Aug 21 2023",
      nhaiDocumentNumber: "NHA51424",
      nhadDocumentValidityTillDate: "Aug 21 2023",
      conopy: "PVC",
      rvi: "Y",
      drivevay: "Y",
      appraochRoad: "Y",
      idSignages: "Y",
      idSignagesIntegratedWithAutomation: "N",
      highMasT: "Y",
      hoardingAvialable: "Y",
      hoardingAvialableNos: "1",
      hoardingAvialableSize: "1200 x 2000",
      salesBuilding: "Y",
      cctv: "Y",
      puc: "Y",
      esd: "Y",
      ESDNos: "2",
      ALDS: "Y",
      ALDSAutomationWithIntegration: "Y",
      CNG: "Y",
      CNGAutomationWithIntegration: "Y",
      CNGDUSerialNumber: "12122133",
      CNGDUMake: "GILBARCO",
      CNGDUType: "GILBARCO",
      CNGNozzles: "4",
      CNGWMalidityTillDate: "Aug 21 2023",
      VRS: "Y",
      BRSAutomaticWithIntegration: "Y",
      VRSVendorName: "FUELTRANS",
      typeVRSSystem: "TYPE",
      EVCharging: "Y",
      EVAutomationWithIntegration: "Y",
      EVSlowChargerCapacity: "40000 KW",
      EVFastChargerCapacity: "10000 KW",
      ddd: "Y",
      DDDIntegrationWithAutomation: "Y",
      solar: "Y",
      solarCapacity: "Y",
      solarCapacityConnectedToGrid: "Y",
      digitelAirTower: "Y",
      airCompressor: "Y",
      ecoFriendlyDieseGeneratorSet: "Y",
      rainWaterHarvesting: "Y",
      itps: "Y",
      edc: "Y",
      EDCBankName: "Y",
      EDCMicNumber: "3434345433",
      EDCTIDNumber: "3434345433",
      noOfEarthPits: "5",
      updatedBy: "Jafar Alhusayn",
      updatedDate: "August 21 2023 11:23 AM",
    },
    {
      roCode: "125242",
      roName: "SUPER SERVICE STATION",
      projectPhase: "P1",
      automaticVendor: "bahwan cybertek",
      tempCloseROModernisation: "No",
      roType: "COCO",
      validLeaseDate: "26 Dec 2035",
      roCategory: "Service station",
      salesArea: "Chennai",
      region: "Chennai",
      zone: "Sounth",
      headOffice: "Chennai",
      address: "Amaravathi Nagar, Udume=ulpet taluk",
      city: "Andigondannur",
      district: "Chennai",
      state: "tamilNadu",
      pincode: "642102",
      dealerName: "GOEL BALRAM",
      delearPhoneNumber: "04252 256 296",
      delearMobileNumber: "9526866705",
      hpclEmailId: "test@gmail.com",
      wmnValidityDate: "jun 20 2029",
      tinNumber: "1212333454333",
      ipAddredd: "122.165.72.86",
      vsatBrodmbandSdvanSimId: "34343434343434",
      vsatBrodmbandSdvanSimId2: "34343434343434",
      lastRoCommunicatedDate: "Aug 21 3023 11:54 AM",
      roStatus: "Active",
      fzdStatsu: "Active",
      locationType: "Urbana",
      highwayNumber: "66",
      highwayState: "12",
      pesoLienseNumber: "AB23233442217878977",
      pesoValidityTillDate: "Aug 21 2023",
      nhaiDocumentNumber: "NHA51424",
      nhadDocumentValidityTillDate: "Aug 21 2023",
      conopy: "PVC",
      rvi: "Y",
      drivevay: "Y",
      appraochRoad: "Y",
      idSignages: "Y",
      idSignagesIntegratedWithAutomation: "N",
      highMasT: "Y",
      hoardingAvialable: "Y",
      hoardingAvialableNos: "1",
      hoardingAvialableSize: "1200 x 2000",
      salesBuilding: "Y",
      cctv: "Y",
      puc: "Y",
      esd: "Y",
      ESDNos: "2",
      ALDS: "Y",
      ALDSAutomationWithIntegration: "Y",
      CNG: "Y",
      CNGAutomationWithIntegration: "Y",
      CNGDUSerialNumber: "12122133",
      CNGDUMake: "GILBARCO",
      CNGDUType: "GILBARCO",
      CNGNozzles: "4",
      CNGWMalidityTillDate: "Aug 21 2023",
      VRS: "Y",
      BRSAutomaticWithIntegration: "Y",
      VRSVendorName: "FUELTRANS",
      typeVRSSystem: "TYPE",
      EVCharging: "Y",
      EVAutomationWithIntegration: "Y",
      EVSlowChargerCapacity: "40000 KW",
      EVFastChargerCapacity: "10000 KW",
      ddd: "Y",
      DDDIntegrationWithAutomation: "Y",
      solar: "Y",
      solarCapacity: "Y",
      solarCapacityConnectedToGrid: "Y",
      digitelAirTower: "Y",
      airCompressor: "Y",
      ecoFriendlyDieseGeneratorSet: "Y",
      rainWaterHarvesting: "Y",
      itps: "Y",
      edc: "Y",
      EDCBankName: "Y",
      EDCMicNumber: "3434345433",
      EDCTIDNumber: "3434345433",
      noOfEarthPits: "5",
      updatedBy: "Jafar Alhusayn",
      updatedDate: "August 21 2023 11:23 AM",
    },
    {
      roCode: "125242",
      roName: "SUPER SERVICE STATION",
      projectPhase: "P1",
      automaticVendor: "bahwan cybertek",
      tempCloseROModernisation: "No",
      roType: "COCO",
      validLeaseDate: "26 Dec 2035",
      roCategory: "Service station",
      salesArea: "Chennai",
      region: "Chennai",
      zone: "Sounth",
      headOffice: "Chennai",
      address: "Amaravathi Nagar, Udume=ulpet taluk",
      city: "Andigondannur",
      district: "Chennai",
      state: "tamilNadu",
      pincode: "642102",
      dealerName: "GOEL BALRAM",
      delearPhoneNumber: "04252 256 296",
      delearMobileNumber: "9526866705",
      hpclEmailId: "test@gmail.com",
      wmnValidityDate: "jun 20 2029",
      tinNumber: "1212333454333",
      ipAddredd: "122.165.72.86",
      vsatBrodmbandSdvanSimId: "34343434343434",
      vsatBrodmbandSdvanSimId2: "34343434343434",
      lastRoCommunicatedDate: "Aug 21 3023 11:54 AM",
      roStatus: "Active",
      fzdStatsu: "Active",
      locationType: "Urbana",
      highwayNumber: "66",
      highwayState: "12",
      pesoLienseNumber: "AB23233442217878977",
      pesoValidityTillDate: "Aug 21 2023",
      nhaiDocumentNumber: "NHA51424",
      nhadDocumentValidityTillDate: "Aug 21 2023",
      conopy: "PVC",
      rvi: "Y",
      drivevay: "Y",
      appraochRoad: "Y",
      idSignages: "Y",
      idSignagesIntegratedWithAutomation: "N",
      highMasT: "Y",
      hoardingAvialable: "Y",
      hoardingAvialableNos: "1",
      hoardingAvialableSize: "1200 x 2000",
      salesBuilding: "Y",
      cctv: "Y",
      puc: "Y",
      esd: "Y",
      ESDNos: "2",
      ALDS: "Y",
      ALDSAutomationWithIntegration: "Y",
      CNG: "Y",
      CNGAutomationWithIntegration: "Y",
      CNGDUSerialNumber: "12122133",
      CNGDUMake: "GILBARCO",
      CNGDUType: "GILBARCO",
      CNGNozzles: "4",
      CNGWMalidityTillDate: "Aug 21 2023",
      VRS: "Y",
      BRSAutomaticWithIntegration: "Y",
      VRSVendorName: "FUELTRANS",
      typeVRSSystem: "TYPE",
      EVCharging: "Y",
      EVAutomationWithIntegration: "Y",
      EVSlowChargerCapacity: "40000 KW",
      EVFastChargerCapacity: "10000 KW",
      ddd: "Y",
      DDDIntegrationWithAutomation: "Y",
      solar: "Y",
      solarCapacity: "Y",
      solarCapacityConnectedToGrid: "Y",
      digitelAirTower: "Y",
      airCompressor: "Y",
      ecoFriendlyDieseGeneratorSet: "Y",
      rainWaterHarvesting: "Y",
      itps: "Y",
      edc: "Y",
      EDCBankName: "Y",
      EDCMicNumber: "3434345433",
      EDCTIDNumber: "3434345433",
      noOfEarthPits: "5",
      updatedBy: "Jafar Alhusayn",
      updatedDate: "August 21 2023 11:23 AM",
    },
    {
      roCode: "125242",
      roName: "SUPER SERVICE STATION",
      projectPhase: "P1",
      automaticVendor: "bahwan cybertek",
      tempCloseROModernisation: "No",
      roType: "COCO",
      validLeaseDate: "26 Dec 2035",
      roCategory: "Service station",
      salesArea: "Chennai",
      region: "Chennai",
      zone: "Sounth",
      headOffice: "Chennai",
      address: "Amaravathi Nagar, Udume=ulpet taluk",
      city: "Andigondannur",
      district: "Chennai",
      state: "tamilNadu",
      pincode: "642102",
      dealerName: "GOEL BALRAM",
      delearPhoneNumber: "04252 256 296",
      delearMobileNumber: "9526866705",
      hpclEmailId: "test@gmail.com",
      wmnValidityDate: "jun 20 2029",
      tinNumber: "1212333454333",
      ipAddredd: "122.165.72.86",
      vsatBrodmbandSdvanSimId: "34343434343434",
      vsatBrodmbandSdvanSimId2: "34343434343434",
      lastRoCommunicatedDate: "Aug 21 3023 11:54 AM",
      roStatus: "Active",
      fzdStatsu: "Active",
      locationType: "Urbana",
      highwayNumber: "66",
      highwayState: "12",
      pesoLienseNumber: "AB23233442217878977",
      pesoValidityTillDate: "Aug 21 2023",
      nhaiDocumentNumber: "NHA51424",
      nhadDocumentValidityTillDate: "Aug 21 2023",
      conopy: "PVC",
      rvi: "Y",
      drivevay: "Y",
      appraochRoad: "Y",
      idSignages: "Y",
      idSignagesIntegratedWithAutomation: "N",
      highMasT: "Y",
      hoardingAvialable: "Y",
      hoardingAvialableNos: "1",
      hoardingAvialableSize: "1200 x 2000",
      salesBuilding: "Y",
      cctv: "Y",
      puc: "Y",
      esd: "Y",
      ESDNos: "2",
      ALDS: "Y",
      ALDSAutomationWithIntegration: "Y",
      CNG: "Y",
      CNGAutomationWithIntegration: "Y",
      CNGDUSerialNumber: "12122133",
      CNGDUMake: "GILBARCO",
      CNGDUType: "GILBARCO",
      CNGNozzles: "4",
      CNGWMalidityTillDate: "Aug 21 2023",
      VRS: "Y",
      BRSAutomaticWithIntegration: "Y",
      VRSVendorName: "FUELTRANS",
      typeVRSSystem: "TYPE",
      EVCharging: "Y",
      EVAutomationWithIntegration: "Y",
      EVSlowChargerCapacity: "40000 KW",
      EVFastChargerCapacity: "10000 KW",
      ddd: "Y",
      DDDIntegrationWithAutomation: "Y",
      solar: "Y",
      solarCapacity: "Y",
      solarCapacityConnectedToGrid: "Y",
      digitelAirTower: "Y",
      airCompressor: "Y",
      ecoFriendlyDieseGeneratorSet: "Y",
      rainWaterHarvesting: "Y",
      itps: "Y",
      edc: "Y",
      EDCBankName: "Y",
      EDCMicNumber: "3434345433",
      EDCTIDNumber: "3434345433",
      noOfEarthPits: "5",
      updatedBy: "Jafar Alhusayn",
      updatedDate: "August 21 2023 11:23 AM",
    },
  ],
};
