export const dummyUsers = {
  paging: {},
  data: [
    {
      roleId: '01',
      userName: 'Superuser',
      firstName: 'Super User',
      middleName: '-',
      LastName: '-',
      phoneNumber: '9526866705',
      password: 'Admin123',
      access: {
        web: true,
        mob: true,
      },
      status: 'Active',
    },
    {
      roleId: '02',
      userName: 'Francine Rivera',
      firstName: 'Francine Rivera',
      middleName: '-',
      LastName: '-',
      phoneNumber: '8547511687',
      password: 'Admin123',
      access: {
        web: true,
        mob: false,
      },
      status: 'Blocked',
    },
  ],
};

export const dummyRoles = {
  paging: {},
  data: [
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
    {
      siteId: '01',
      siteName: 'JILU AUTO GAS',
      zone: 'North',
      region: 'Region 01',
      salesArea: 'Sales Area 1',
    },
  ],
};
